- name: use template
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: copy a file
      copy:
        src: test_file
        dest: /tmp/copy-file

    - name: use template file
      template:
        src: test_file
        dest: /tmp/template-file
