- name: using handlers
  hosts: all
  become: yes
  tasks:
    - name: install the package
      yum:
        name: httpd
        state: latest
    - name: print hi
      debug:
        msg: " hello there "
      notify:
        - hand1
      changed_when: true
  handlers:
    - name: hand1
      service:
        name: httpd
        state: started
        enabled: yes
